# -*- mode: ruby -*-
# vi: set ft=ruby :

# MULTI VMS

Vagrant.configure("2") do |config|
  (1..2).each do |i|
    config.vm.define "graylog_#{i}" do |mongo|
      mongo.vm.box = "centos/7"
      mongo.vm.network "public_network", bridge: "wlp2s0"
    end
  end
end