# -*- mode: ruby -*-
# vi: set ft=ruby :

# VM Instalação Apache via Script Shell

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "public_network", bridge: "enp1s0f1"
  config.vm.provision "shell", path: "apache.sh"
end
